/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddItem: typeof import('./src/fragments/AddItem.vue')['default']
    Calculator: typeof import('./src/components/Calculator.vue')['default']
    CreateRecord: typeof import('./src/fragments/CreateRecord.vue')['default']
    DeleteItem: typeof import('./src/fragments/DeleteItem.vue')['default']
    DeleteRecord: typeof import('./src/fragments/DeleteRecord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateItem: typeof import('./src/fragments/UpdateItem.vue')['default']
    UpdateRecord: typeof import('./src/fragments/UpdateRecord.vue')['default']
  }
}
