/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddItem: typeof import('./src/fragments/Items/AddItem.vue')['default']
    CreateRecord: typeof import('./src/fragments/Record/CreateRecord.vue')['default']
    DeleteItem: typeof import('./src/fragments/Items/DeleteItem.vue')['default']
    DeleteRecord: typeof import('./src/fragments/Record/DeleteRecord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateItem: typeof import('./src/fragments/Items/UpdateItem.vue')['default']
    UpdateRecord: typeof import('./src/fragments/Record/UpdateRecord.vue')['default']
  }
}
